name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Adjust Ruby version if needed

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
          npm ci

      - name: Build Jekyll Site
        run: npm run build

      - name: Deploy via SCP
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          scp -r build/* "$DEPLOY_USER@$DEPLOY_HOST:/www/kaculik.cz"

